num = int(input("type a number:"))
print('-'*20)
print('number {} table'.format(num))
print('{} x  0\t= {}'.format(num, num*0))
print('{} x  1\t= {}'.format(num, num*1))
print('{} x  2\t= {}'.format(num, num*2))
print('{} x  3\t= {}'.format(num, num*3))
print('{} x  4\t= {}'.format(num, num*4))
print('{} x  5\t= {}'.format(num, num*5))
print('{} x  6\t= {}'.format(num, num*6))
print('{} x  7\t= {}'.format(num, num*7))
print('{} x  8\t= {}'.format(num, num*8))
print('{} x  9\t= {}'.format(num, num*9))
print('{} x 10\t= {}'.format(num, num*10))
print('-'*20)