mens = input('Type something:')
print(f'the data type of {mens} is {type(mens)}')
print(f'the text is space: {mens.isspace()}')
print(f'the text is number: {mens.isnumeric()}')
print(f'the text is letter: {mens.isalpha()}')
print(f'the text is alphanumeric: {mens.isalnum()}')
print(f'the text is lower case: {mens.islower()}')
print(f'the text is upper case: {mens.isupper()}')
print(f'the text is capital letter: {mens.istitle()}')
